// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Grzk8ghp1llqWvSKKSvSNUjIVTqdDN4',
    appId: '1:619573714111:web:329d759cedc6455e407a0a',
    messagingSenderId: '619573714111',
    projectId: 'test1-7db62',
    authDomain: 'test1-7db62.firebaseapp.com',
    storageBucket: 'test1-7db62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4nAP7vV6lhUO7hA0fkiqOaHnnvfmdMk',
    appId: '1:619573714111:android:544398dfbf6afbc0407a0a',
    messagingSenderId: '619573714111',
    projectId: 'test1-7db62',
    storageBucket: 'test1-7db62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNmpl8XIeL1xEJ0CDVULBetJhsLN4qKZ8',
    appId: '1:619573714111:ios:58bd1755599bede1407a0a',
    messagingSenderId: '619573714111',
    projectId: 'test1-7db62',
    storageBucket: 'test1-7db62.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNmpl8XIeL1xEJ0CDVULBetJhsLN4qKZ8',
    appId: '1:619573714111:ios:286361997957b6e7407a0a',
    messagingSenderId: '619573714111',
    projectId: 'test1-7db62',
    storageBucket: 'test1-7db62.appspot.com',
    iosBundleId: 'com.example.firebase2.RunnerTests',
  );
}
